import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'English' | 'हिन्दी' | 'తెలుగు' | 'ಕನ್ನಡ' | 'தமிழ்' | 'मराठी' | 'বাংলা' | 'ਪੰਜਾਬੀ';

type Translations = {
    [key in Language]: {
        greeting: string;
        subtitle: string;
        card_scan: string;
        card_scan_sub: string;
        card_advisory: string;
        card_advisory_sub: string;
        card_diary: string;
        card_diary_sub: string;
        card_risk: string;
        card_risk_sub: string;
        card_lunar: string;
        card_lunar_sub: string;
        nav_home: string;
        nav_scan: string;
        nav_diary: string;
        nav_voice: string;
        fab_ask: string;
        live: string;
        coming_soon: string;
        ai_online: string;
        all_features: string;
        available_now: string;
        coming_soon_section: string;
        ai_mode_toggle: string;
        ai_mode_live: string;
        ai_mode_offline: string;
        // New keys for Crop Diary
        journal_title: string;
        journal_sub: string;
        history_btn: string;
        live_ai_advice: string;
        offline_ai_advice: string;
        loading_chat: string;
        loading_insights: string;
        no_insights: string;
        empty_today: string;
        input_placeholder_listening: string;
        input_placeholder_default: string;
        confirm_delete: string;
        read_more: string;
        show_less: string;
        history_sidebar_title: string;
        history_sidebar_empty: string;
        // New keys for MandiVoice
        mandi_title: string;
        mandi_subtitle: string;
        mandi_select_state: string;
        mandi_choose_state: string;
        mandi_enter_crop: string;
        mandi_how_many_bags: string;
        mandi_get_price: string;
        mandi_nearby_mandis: string;
        mandi_listen_advice: string;
        mandi_share_advice: string;
        // New keys for ScanCrop
        scan_title: string;
        scan_subtitle: string;
        scan_take_photo: string;
        scan_upload: string;
        scan_button: string;
        scan_select_state: string;
        scan_confidence: string;
        scan_treatment: string;
        scan_organic: string;
        scan_chemical: string;
        scan_prevention: string;
        scan_nearby: string;
        scan_listen: string;
        scan_recent: string;
        scan_severity_low: string;
        scan_severity_medium: string;
        scan_severity_high: string;
        // Crop names
        crop_wheat: string;
        crop_rice: string;
        crop_maize: string;
        crop_cotton: string;
        crop_soybean: string;
        crop_tomato: string;
        crop_onion: string;
        crop_potato: string;
        // States
        state_maharashtra: string;
        state_punjab: string;
        state_haryana: string;
        state_up: string;
        state_mp: string;
        state_rajasthan: string;
        state_bihar: string;
        state_gujarat: string;
        state_karnataka: string;
        state_ap: string;
    }
};

const translations: Translations = {
    English: {
        greeting: 'Namaste, Anna',
        subtitle: 'How can Krishi-Saathi help you today?',
        card_scan: 'Disease Scan',
        card_scan_sub: 'Detect crop disease instantly',
        card_advisory: 'Voice Market Price',
        card_advisory_sub: 'Speak to get real-time crop price & selling advice',
        card_diary: 'Crop Diary',
        card_diary_sub: 'Track activities and expenses',
        card_risk: 'Risk Alerts',
        card_risk_sub: 'AI-powered warnings',
        card_lunar: 'Lunar Planting',
        card_lunar_sub: 'Smart calendar guide',
        nav_home: 'Home',
        nav_scan: 'Scan Crop',
        nav_diary: 'Crop Diary',
        nav_voice: 'Mandi Voice',
        fab_ask: 'Ask Sahayak',
        live: 'LIVE',
        coming_soon: 'Coming Soon',
        ai_online: 'AI ONLINE',
        all_features: 'All Features',
        available_now: 'Available Now',
        coming_soon_section: 'Coming Soon',
        ai_mode_toggle: 'AI Mode',
        ai_mode_live: 'Live AI Support',
        ai_mode_offline: 'Offline AI Mode',
        journal_title: 'Farm Journal',
        journal_sub: 'Record your field activities today.',
        history_btn: 'History',
        live_ai_advice: 'Live AI Farm Advice',
        offline_ai_advice: 'Offline AI Farm Advice',
        loading_chat: 'Loading chat...',
        loading_insights: 'Loading insights...',
        no_insights: 'Add farm activities to unlock AI insights.',
        empty_today: "Tap the mic or type below to record today's farm activity 🌾",
        input_placeholder_listening: 'Listening...',
        input_placeholder_default: 'What did you do on the farm today?',
        confirm_delete: 'Are you sure you want to delete this entry?',
        read_more: 'Read more',
        show_less: 'Show less',
        history_sidebar_title: 'Journal History',
        history_sidebar_empty: 'No past entries found.',
        mandi_title: 'Mandi Voice',
        mandi_subtitle: 'Ask about any crop — AI gives real market advice',
        mandi_select_state: '📍 Select your State',
        mandi_choose_state: 'Choose a state…',
        mandi_enter_crop: 'Enter Crop Name',
        mandi_how_many_bags: 'How many bags?',
        mandi_get_price: 'Get Price & Advice',
        mandi_nearby_mandis: '📍 Nearby Mandis',
        mandi_listen_advice: 'Listen to Advice',
        mandi_share_advice: 'Share Advice',
        scan_title: 'Scan Crop',
        scan_subtitle: 'Detect crop disease instantly from a photo',
        scan_take_photo: 'Take Photo',
        scan_upload: 'Upload Photo',
        scan_button: 'Scan Now',
        scan_select_state: 'Select your State',
        scan_confidence: 'Confidence',
        scan_treatment: 'Treatment Advice',
        scan_organic: 'Organic Treatment',
        scan_chemical: 'Chemical Treatment',
        scan_prevention: 'Prevention Measures',
        scan_nearby: 'Nearby Agricultural Shops',
        scan_listen: 'Listen to Diagnosis',
        scan_recent: 'Recent Scans',
        scan_severity_low: 'Low Severity',
        scan_severity_medium: 'Medium Severity',
        scan_severity_high: 'High Severity',
        crop_wheat: 'Wheat',
        crop_rice: 'Rice',
        crop_maize: 'Maize',
        crop_cotton: 'Cotton',
        crop_soybean: 'Soybean',
        crop_tomato: 'Tomato',
        crop_onion: 'Onion',
        crop_potato: 'Potato',
        state_maharashtra: 'Maharashtra',
        state_punjab: 'Punjab',
        state_haryana: 'Haryana',
        state_up: 'Uttar Pradesh',
        state_mp: 'Madhya Pradesh',
        state_rajasthan: 'Rajasthan',
        state_bihar: 'Bihar',
        state_gujarat: 'Gujarat',
        state_karnataka: 'Karnataka',
        state_ap: 'Andhra Pradesh',
    },
    'हिन्दी': {
        greeting: 'नमस्ते, अन्ना',
        subtitle: 'कृषि-साथी आज आपकी कैसे मदद कर सकता है?',
        card_scan: 'रोग स्कैन',
        card_scan_sub: 'तत्काल फसल रोग का पता लगाएं',
        card_advisory: 'आवाज़ में बाजार भाव',
        card_advisory_sub: 'वास्तविक समय में फसल की कीमत जानने के लिए बोलें',
        card_diary: 'फसल डायरी',
        card_diary_sub: 'गतिविधियों और खर्चों को ट्रैक करें',
        card_risk: 'जोखिम चेतावनी',
        card_risk_sub: 'एआई-संचालित चेतावनियाँ',
        card_lunar: 'चंद्र रोपण',
        card_lunar_sub: 'स्मार्ट कैलेंडर गाइड',
        nav_home: 'होम',
        nav_scan: 'फसल स्कैन',
        nav_diary: 'फसल डायरी',
        nav_voice: 'वॉयस क्रॉप',
        fab_ask: 'सहायक से पूछें',
        live: 'लाइव',
        coming_soon: 'जल्द आ रहा है',
        ai_online: 'एआई ऑनलाइन',
        all_features: 'सभी सुविधाएँ',
        available_now: 'अब उपलब्ध है',
        coming_soon_section: 'जल्द आ रहा है',
        ai_mode_toggle: 'एआई मोड',
        ai_mode_live: 'लाइव एआई सपोर्ट',
        ai_mode_offline: 'ऑफ़लाइन एआई मोड',
        journal_title: 'फसल डायरी',
        journal_sub: 'आज की अपनी खेत की गतिविधियां दर्ज करें।',
        history_btn: 'इतिहास',
        live_ai_advice: 'लाइव एआई कृषि सलाह',
        offline_ai_advice: 'ऑफ़लाइन एआई कृषि सलाह',
        loading_chat: 'चैट लोड हो रहा है...',
        loading_insights: 'अंतर्दृष्टि लोड हो रही है...',
        no_insights: 'एआई अंतर्दृष्टि अनलॉक करने के लिए खेत की गतिविधियां जोड़ें।',
        empty_today: "खेत की गतिविधि दर्ज करने के लिए माइक पर टैप करें या नीचे टाइप करें 🌾",
        input_placeholder_listening: 'सुन रहा है...',
        input_placeholder_default: 'आज आपने खेत में क्या किया?',
        confirm_delete: 'क्या आप वाकई इस प्रविष्टि को हटाना चाहते हैं?',
        read_more: 'और पढ़ें',
        show_less: 'कम दिखाएं',
        history_sidebar_title: 'डायरी इतिहास',
        history_sidebar_empty: 'कोई पिछली प्रविष्टि नहीं मिली।',
        mandi_title: 'मंडी वॉयस',
        mandi_subtitle: 'किसी भी फसल के बारे में पूछें - एआई बाजार की सलाह देता है',
        mandi_select_state: '📍 अपना राज्य चुनें',
        mandi_choose_state: 'एक राज्य चुनें…',
        mandi_enter_crop: 'फसल का नाम दर्ज करें',
        mandi_how_many_bags: 'कितनी बोरियां?',
        mandi_get_price: 'कीमत और सलाह प्राप्त करें',
        mandi_nearby_mandis: '📍 आस-पास की मंडियां',
        mandi_listen_advice: 'सलाह सुनें',
        mandi_share_advice: 'सलाह साझा करें',
        scan_title: 'फसल स्कैन करें',
        scan_subtitle: 'फोटो से बीमारी तुरंत पहचानें',
        scan_take_photo: 'फोटो लें',
        scan_upload: 'फोटो अपलोड करें',
        scan_button: 'अभी स्कैन करें',
        scan_select_state: 'अपना राज्य चुनें',
        scan_confidence: 'विश्वसनीयता',
        scan_treatment: 'उपचार सलाह',
        scan_organic: 'जैविक उपचार',
        scan_chemical: 'रासायनिक उपचार',
        scan_prevention: 'बचाव के उपाय',
        scan_nearby: 'नजदीकी कृषि दुकानें',
        scan_listen: 'निदान सुनें',
        scan_recent: 'हाल के स्कैन',
        scan_severity_low: 'कम गंभीर',
        scan_severity_medium: 'मध्यम गंभीर',
        scan_severity_high: 'अधिक गंभीर',
        crop_wheat: 'गेहूं',
        crop_rice: 'चावल',
        crop_maize: 'मक्का',
        crop_cotton: 'कपास',
        crop_soybean: 'सोयाबीन',
        crop_tomato: 'टमाटर',
        crop_onion: 'प्याज',
        crop_potato: 'आलू',
        state_maharashtra: 'महाराष्ट्र',
        state_punjab: 'पंजाब',
        state_haryana: 'हरियाणा',
        state_up: 'उत्तर प्रदेश',
        state_mp: 'मध्य प्रदेश',
        state_rajasthan: 'राजस्थान',
        state_bihar: 'बिहार',
        state_gujarat: 'गुजरात',
        state_karnataka: 'कर्नाटक',
        state_ap: 'आंध्र प्रदेश',
    },
    'తెలుగు': {
        greeting: 'నమస్తే, అన్న',
        subtitle: 'కృషి-సారథి ఈరోజు మీకు ఎలా సహాయపడగలదు?',
        card_scan: 'వ్యాధి స్కాన్',
        card_scan_sub: 'పంట వ్యాధిని తక్షణమే గుర్తించండి',
        card_advisory: 'వాయిస్ మార్కెట్ ధర',
        card_advisory_sub: 'నిజ-సమయ పంట ధర కోసం మాట్లాడండి',
        card_diary: 'పంట డైరీ',
        card_diary_sub: 'కార్యకలాపాలు మరియు ఖర్చులను ట్రాక్ చేయండి',
        card_risk: 'ప్రమాద హెచ్చరికలు',
        card_risk_sub: 'AI-ఆధారిత హెచ్చరికలు',
        card_lunar: 'Lunar Planting',
        card_lunar_sub: 'Smart calendar guide',
        nav_home: 'హోమ్',
        nav_scan: 'పంట స్కాన్',
        nav_diary: 'పంట డైరీ',
        nav_voice: 'వాయిస్ క్రాప్',
        fab_ask: 'సహాయక్ ను అడగండి',
        live: 'లైవ్',
        coming_soon: 'త్వరలో',
        ai_online: 'AI ఆన్‌లైన్‌లో ఉంది',
        all_features: 'అన్ని ఫీచర్లు',
        available_now: 'ఇప్పుడు అందుబాటులో ఉంది',
        coming_soon_section: 'త్వరలో',
        ai_mode_toggle: 'AI మోడ్',
        ai_mode_live: 'లైవ్ AI సపోర్ట్',
        ai_mode_offline: 'ఆఫ్‌లైన్ AI మోడ్',
        journal_title: 'పంట డైరీ',
        journal_sub: 'ఈరోజు మీ వ్యవసాయ పనులను రికార్డ్ చేయండి.',
        history_btn: 'చరిత్ర',
        live_ai_advice: 'లైవ్ AI పంట సలహా',
        offline_ai_advice: 'ఆఫ్‌లైన్ AI పంట సలహా',
        loading_chat: 'చాట్ లోడ్ అవుతోంది...',
        loading_insights: 'అంతర్దృష్టులు లోడ్ అవుతున్నాయి...',
        no_insights: 'AI సలహాలను పొందడానికి వ్యవసాయ పనులను జోడించండి.',
        empty_today: "ఈరోజుటి వ్యవసాయ పనిని రికార్డ్ చేయడానికి మైక్‌ని నొక్కండి లేదా కింద టైప్ చేయండి 🌾",
        input_placeholder_listening: 'వింటున్నాను...',
        input_placeholder_default: 'ఈరోజు మీరు పొలంలో ఏం చేశారు?',
        confirm_delete: 'మీరు ఖచ్చితంగా దీన్ని తొలగించాలనుకుంటున్నారా?',
        read_more: 'మరింత చదవండి',
        show_less: 'తక్కువ చూపించు',
        history_sidebar_title: 'డైరీ చరిత్ర',
        history_sidebar_empty: 'గత నమోదులేవీ కనుగొనబడలేదు.',
        mandi_title: 'మండి వాయిస్',
        mandi_subtitle: 'ఏదైనా పంట గురించి అడగండి - AI మార్కెట్ సలహా ఇస్తుంది',
        mandi_select_state: '📍 మీ రాష్ట్రాన్ని ఎంచుకోండి',
        mandi_choose_state: 'ఒక రాష్ట్రాన్ని ఎంచుకోండి…',
        mandi_enter_crop: 'పంట పేరు నమోదు చేయండి',
        mandi_how_many_bags: 'ఎన్ని బస్తాలు?',
        mandi_get_price: 'ధర కనుక్కోండి & సలహా పొందండి',
        mandi_nearby_mandis: '📍 సమీప మండీలు',
        mandi_listen_advice: 'సలహా వినండి',
        mandi_share_advice: 'సలహా పంచుకోండి',
        scan_title: 'పంటను స్కాన్ చేయండి',
        scan_subtitle: 'ఫోటో ద్వారా వ్యాధిని వెంటనే గుర్తించండి',
        scan_take_photo: 'ఫోటో తీయండి',
        scan_upload: 'ఫోటో అప్లోడ్ చేయండి',
        scan_button: 'ఇప్పుడు స్కాన్ చేయండి',
        scan_select_state: 'మీ రాష్ట్రాన్ని ఎంచుకోండి',
        scan_confidence: 'నమ్మకం',
        scan_treatment: 'చికిత్స సలహా',
        scan_organic: 'సేంద్రీయ చికిత్స',
        scan_chemical: 'రసాయన చికిత్స',
        scan_prevention: 'నివారణ చర్యలు',
        scan_nearby: 'సమీప వ్యవసాయ దుకాణాలు',
        scan_listen: 'రోగ నిర్ధారణ వినండి',
        scan_recent: 'ఇటీవలి స్కాన్లు',
        scan_severity_low: 'తక్కువ తీవ్రత',
        scan_severity_medium: 'మధ్యస్థ తీవ్రత',
        scan_severity_high: 'అధిక తీవ్రత',
        crop_wheat: 'గోధుమ',
        crop_rice: 'వరి',
        crop_maize: 'మొక్కజొన్న',
        crop_cotton: 'పత్తి',
        crop_soybean: 'సోయాబీన్',
        crop_tomato: 'టమాటా',
        crop_onion: 'ఉల్లిపాయ',
        crop_potato: 'బంగాళాదుంప',
        state_maharashtra: 'మహారాష్ట్ర',
        state_punjab: 'పంజాబ్',
        state_haryana: 'హర్యానా',
        state_up: 'ఉత్తర్ ప్రదేశ్',
        state_mp: 'మధ్యప్రదేశ్',
        state_rajasthan: 'రాజస్థాన్',
        state_bihar: 'బీహార్',
        state_gujarat: 'గుజరాత్',
        state_karnataka: 'కర్ణాటక',
        state_ap: 'ఆంధ్రప్రదేశ్',
    },
    'ಕನ್ನಡ': {
        greeting: 'ನಮಸ್ತೆ, ಅಣ್ಣ',
        subtitle: 'ಕೃಷಿ-ಸಾಥಿ ಇಂದು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
        card_scan: 'ರೋಗ ಸ್ಕ್ಯಾನ್',
        card_scan_sub: 'ಬೆಳೆ ರೋಗವನ್ನು ತಕ್ಷಣ ಪತ್ತೆಹಚ್ಚಿ',
        card_advisory: 'ಧ್ವನಿ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
        card_advisory_sub: 'ನೈಜ-ಸಮಯದ ಬೆಳೆ ಬೆಲೆಗಾಗಿ ಮಾತನಾಡಿ',
        card_diary: 'ಬೆಳೆ ಡೈರಿ',
        card_diary_sub: 'ಚಟುವಟಿಕೆಗಳು ಮತ್ತು ವೆಚ್ಚಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
        card_risk: 'ಅಪಾಯದ ಎಚ್ಚರಿಕೆಗಳು',
        card_risk_sub: 'AI-ಆಧಾರಿತ ಎಚ್ಚರಿಕೆಗಳು',
        card_lunar: 'Lunar Planting',
        card_lunar_sub: 'Smart calendar guide',
        nav_home: 'ಮುಖಪುಟ',
        nav_scan: 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್',
        nav_diary: 'ಬೆಳೆ ಡೈರಿ',
        nav_voice: 'ಧ್ವನಿ ಬೆಳೆ',
        fab_ask: 'ಸಹಾಯಕ್ ಕೇಳಿ',
        live: 'ಲೈವ್',
        coming_soon: 'ಶೀಘ್ರದಲ್ಲೇ',
        ai_online: 'AI ಆನ್‌ಲೈನ್‌ನಲ್ಲಿದೆ',
        all_features: 'ಎಲ್ಲಾ ವೈಶಿಷ್ಟ್ಯಗಳು',
        available_now: 'ಈಗ ಲಭ್ಯವಿದೆ',
        coming_soon_section: 'ಶೀಘ್ರದಲ್ಲೇ',
        ai_mode_toggle: 'AI ಮೋಡ್',
        ai_mode_live: 'ಲೈವ್ AI ಬೆಂಬಲ',
        ai_mode_offline: 'ಆಫ್‌ಲೈನ್ AI ಮೋಡ್',
        journal_title: 'ಕೃಷಿ ಜರ್ನಲ್',
        journal_sub: 'ಇಂದು ನಿಮ್ಮ ಕೃಷಿ ಚಟುವಟಿಕೆಗಳನ್ನು ದಾಖಲಿಸಿ.',
        history_btn: 'ಇತಿಹಾಸ',
        live_ai_advice: 'ಲೈವ್ AI ಕೃಷಿ ಸಲಹೆ',
        offline_ai_advice: 'ಆಫ್‌ಲೈನ್ AI ಕೃಷಿ ಸಲಹೆ',
        loading_chat: 'ಚಾಟ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
        loading_insights: 'ಒಳನೋಟಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
        no_insights: 'AI ಒಳನೋಟಗಳನ್ನು ಅನ್ಲಾಕ್ ಮಾಡಲು ಕೃಷಿ ಚಟುವಟಿಕೆಗಳನ್ನು ಸೇರಿಸಿ.',
        empty_today: "ಇಂದಿನ ಕೃಷಿ ಚಟುವಟಿಕೆಯನ್ನು ದಾಖಲಿಸಲು ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ ಅಥವಾ ಕೆಳಗೆ ಟೈಪ್ ಮಾಡಿ 🌾",
        input_placeholder_listening: 'ಆಲಿಸುತ್ತಿದೆ...',
        input_placeholder_default: 'ಇಂದು ನೀವು ಹೊಲದಲ್ಲಿ ಏನು ಮಾಡಿದ್ದೀರಿ?',
        confirm_delete: 'ಖಂಡಿತವಾಗಿಯೂ ಈ ನಮೂದನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?',
        read_more: 'ಮತ್ತಷ್ಟು ಓದಿ',
        show_less: 'ಕಡಿಮೆ ತೋರಿಸಿ',
        history_sidebar_title: 'ಡೈರಿ ಇತಿಹಾಸ',
        history_sidebar_empty: 'ಯಾವುದೇ ಹಿಂದಿನ ನಮೂದುಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
        mandi_title: 'ಮಂಡಿ ಧ್ವನಿ',
        mandi_subtitle: 'ಯಾವುದೇ ಬೆಳೆಯ ಬಗ್ಗೆ ಕೇಳಿ - AI ಮಾರುಕಟ್ಟೆ ಸಲಹೆ ನೀಡುತ್ತದೆ',
        mandi_select_state: '📍 ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        mandi_choose_state: 'ಒಂದು ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ…',
        mandi_enter_crop: 'ಬೆಳೆಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
        mandi_how_many_bags: 'ಎಷ್ಟು ಚೀಲಗಳು?',
        mandi_get_price: 'ಬೆಲೆ ಮತ್ತು ಸಲಹೆ ಪಡೆಯಿರಿ',
        mandi_nearby_mandis: '📍 ಹತ್ತಿರದ ಮಂಡಿಗಳು',
        mandi_listen_advice: 'ಸಲಹೆಯನ್ನು ಆಲಿಸಿ',
        mandi_share_advice: 'ಸಲಹೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
        scan_title: 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
        scan_subtitle: 'ಫೋಟೋದಿಂದ ರೋಗವನ್ನು ತಕ್ಷಣ ಗುರುತಿಸಿ',
        scan_take_photo: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
        scan_upload: 'ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
        scan_button: 'ಈಗ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
        scan_select_state: 'ನಿಮ್ಮ ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ',
        scan_confidence: 'ವಿಶ್ವಾಸಾರ್ಹತೆ',
        scan_treatment: 'ಚಿಕಿತ್ಸೆ ಸಲಹೆ',
        scan_organic: 'ಸಾವಯವ ಚಿಕಿತ್ಸೆ',
        scan_chemical: 'ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ',
        scan_prevention: 'ತಡೆಗಟ್ಟುವ ಕ್ರಮಗಳು',
        scan_nearby: 'ಹತ್ತಿರದ ಕೃಷಿ ಅಂಗಡಿಗಳು',
        scan_listen: 'ರೋಗನಿರ್ಣಯ ಕೇಳಿ',
        scan_recent: 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್ಗಳು',
        scan_severity_low: 'ಕಡಿಮೆ ತೀವ್ರತೆ',
        scan_severity_medium: 'ಮಧ್ಯಮ ತೀವ್ರತೆ',
        scan_severity_high: 'ಹೆಚ್ಚು ತೀವ್ರತೆ',
        crop_wheat: 'ಗೋಧಿ',
        crop_rice: 'ಅಕ್ಕಿ',
        crop_maize: 'ಜೋಳ',
        crop_cotton: 'ಹತ್ತಿ',
        crop_soybean: 'ಸೋಯಾಬೀನ್',
        crop_tomato: 'ಟೊಮೇಟೊ',
        crop_onion: 'ಈರುಳ್ಳಿ',
        crop_potato: 'ಆಲೂಗಡ್ಡೆ',
        state_maharashtra: 'ಮಹಾರಾಷ್ಟ್ರ',
        state_punjab: 'ಪಂಜಾಬ್',
        state_haryana: 'ಹರಿಯಾಣ',
        state_up: 'ಉತ್ತರ ಪ್ರದೇಶ',
        state_mp: 'ಮಧ್ಯ ಪ್ರದೇಶ',
        state_rajasthan: 'ರಾಜಸ್ಥಾನ',
        state_bihar: 'ಬಿಹಾರ',
        state_gujarat: 'ಗುಜರಾತ್',
        state_karnataka: 'ಕರ್ನಾಟಕ',
        state_ap: 'ಆಂಧ್ರ ಪ್ರದೇಶ',
    },
    'தமிழ்': {
        greeting: 'வணக்கம், அண்ணா',
        subtitle: 'கிரிஷி-சாத்தி இன்று உங்களுக்கு எப்படி உதவ முடியும்?',
        card_scan: 'நோய் ஸ்கேன்',
        card_scan_sub: 'பயிர் நோயை உடனடியாக கண்டறியவும்',
        card_advisory: 'குரல் சந்தை விலை',
        card_advisory_sub: 'நிகழ்நேர பயிர் விலைக்கு பேசவும்',
        card_diary: 'பயிர் டைரி',
        card_diary_sub: 'செயல்பாடுகள் மற்றும் செலவுகளைக் கண்காணிக்கவும்',
        card_risk: 'அபாய எச்சரிக்கைகள்',
        card_risk_sub: 'AI எச்சரிக்கைகள்',
        card_lunar: 'Lunar Planting',
        card_lunar_sub: 'Smart calendar guide',
        nav_home: 'முகப்பு',
        nav_scan: 'பயிர் ஸ்கேன்',
        nav_diary: 'பயிர் டைரி',
        nav_voice: 'குரல் பயிர்',
        fab_ask: 'சஹாயக்கிடம் கேளுங்கள்',
        live: 'நேரலை',
        coming_soon: 'விரைவில்',
        ai_online: 'AI ஆன்லைனில் உள்ளது',
        all_features: 'அனைத்து அம்சங்கள்',
        available_now: 'இப்போது கிடைக்கும்',
        coming_soon_section: 'விரைவில்',
        ai_mode_toggle: 'AI பயன்முறை',
        ai_mode_live: 'நேரடி AI ஆதரவு',
        ai_mode_offline: 'ஆஃப்லைன் AI பயன்முறை',
        journal_title: 'பண்ணை நாட்குறிப்பு',
        journal_sub: 'இன்று உங்கள் பண்ணை நடவடிக்கைகளை பதிவு செய்யவும்.',
        history_btn: 'வரலாறு',
        live_ai_advice: 'நேரடி AI பண்ணை ஆலோசனை',
        offline_ai_advice: 'ஆஃப்லைன் AI பண்ணை ஆலோசனை',
        loading_chat: 'உரையாடல் ஏற்றப்படுகிறது...',
        loading_insights: 'நுண்ணறிவுகள் ஏற்றப்படுகின்றன...',
        no_insights: 'AI நுண்ணறிவுகளைப் பெற பண்ணை நடவடிக்கைகளைச் சேர்க்கவும்.',
        empty_today: "இன்றைய பண்ணை நடவடிக்கையை பதிவு செய்ய மைக்கைத் தட்டவும் அல்லது கீழே தட்டச்சு செய்யவும் 🌾",
        input_placeholder_listening: 'கேட்கிறது...',
        input_placeholder_default: 'இன்று நீங்கள் பண்ணையில் என்ன செய்தீர்கள்?',
        confirm_delete: 'நிச்சயமாக இதை நீக்க விரும்புகிறீர்களா?',
        read_more: 'மேலும் படிக்க',
        show_less: 'குறைவாகக் காட்டு',
        history_sidebar_title: 'நாட்குறிப்பு வரலாறு',
        history_sidebar_empty: 'கடந்த பதிவுகள் எதுவும் இல்லை.',
        mandi_title: 'மண்டி குரல்',
        mandi_subtitle: 'எந்தவொரு பயிர் பற்றியும் கேளுங்கள் - AI சந்தை ஆலோசனையை வழங்குகிறது',
        mandi_select_state: '📍 உங்கள் மாநிலத்தை தேர்ந்தெடுக்கவும்',
        mandi_choose_state: 'ஒரு மாநிலத்தை தேர்ந்தெடுக்கவும்…',
        mandi_enter_crop: 'பயிர் பெயரை உள்ளிடவும்',
        mandi_how_many_bags: 'எத்தனை மூட்டைகள்?',
        mandi_get_price: 'விலை மற்றும் ஆலோசனையைப் பெறுங்கள்',
        mandi_nearby_mandis: '📍 அருகிலுள்ள மண்டிகள்',
        mandi_listen_advice: 'ஆலோசனையைக் கேளுங்கள்',
        mandi_share_advice: 'ஆலோசனையை பகிரவும்',
        scan_title: 'பயிரை ஸ்கேன் செய்யுங்கள்',
        scan_subtitle: 'புகைப்படத்தில் நோயை உடனே கண்டறியுங்கள்',
        scan_take_photo: 'புகைப்படம் எடுங்கள்',
        scan_upload: 'புகைப்படம் பதிவேற்றுங்கள்',
        scan_button: 'இப்போது ஸ்கேன் செய்யுங்கள்',
        scan_select_state: 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுங்கள்',
        scan_confidence: 'நம்பகத்தன்மை',
        scan_treatment: 'சிகிச்சை ஆலோசனை',
        scan_organic: 'இயற்கை சிகிச்சை',
        scan_chemical: 'இரசாயன சிகிச்சை',
        scan_prevention: 'தடுப்பு நடவடிக்கைகள்',
        scan_nearby: 'அருகிலுள்ள விவசாய கடைகள்',
        scan_listen: 'நோய் கண்டறிதலைக் கேளுங்கள்',
        scan_recent: 'சமீபத்திய ஸ்கேன்கள்',
        scan_severity_low: 'குறைந்த தீவிரம்',
        scan_severity_medium: 'நடுத்தர தீவிரம்',
        scan_severity_high: 'அதிக தீவிரம்',
        crop_wheat: 'கோதுமை',
        crop_rice: 'அரிசி',
        crop_maize: 'மக்காச்சோளம்',
        crop_cotton: 'பருத்தி',
        crop_soybean: 'சோயாபீன்',
        crop_tomato: 'தக்காளி',
        crop_onion: 'வெங்காயம்',
        crop_potato: 'உருளைக்கிழங்கு',
        state_maharashtra: 'மகாராஷ்டிரா',
        state_punjab: 'பஞ்சாப்',
        state_haryana: 'ஹரியானா',
        state_up: 'உத்தர பிரதேசம்',
        state_mp: 'மத்திய பிரதேசம்',
        state_rajasthan: 'ராஜஸ்தான்',
        state_bihar: 'பீகார்',
        state_gujarat: 'குஜராத்',
        state_karnataka: 'கர்நாடகா',
        state_ap: 'ஆந்திரப் பிரதேசம்',
    },
    'मराठी': {
        greeting: 'नमस्ते, अण्णा',
        subtitle: 'कृषी-साथी आज तुमची कशी मदत करू शकतो?',
        card_scan: 'रोग स्कॅन',
        card_scan_sub: 'पीक रोग त्वरित शोधा',
        card_advisory: 'आवाज बाजार भाव',
        card_advisory_sub: 'रिअल-टाइम पीक किंमतीसाठी बोला',
        card_diary: 'पीक डायरी',
        card_diary_sub: 'क्रियाकलाप आणि खर्चाचा मागोवा घ्या',
        card_risk: 'धोका इशारे',
        card_risk_sub: 'AI-आधारित इशारे',
        card_lunar: 'चंद्र रोपण',
        card_lunar_sub: 'स्मार्ट कॅलेंडर मार्गदर्शक',
        nav_home: 'होम',
        nav_scan: 'पीक स्कॅन',
        nav_diary: 'पीक डायरी',
        nav_voice: 'व्हॉइस क्रॉप',
        fab_ask: 'सहाय्यक विचारा',
        live: 'थेट',
        coming_soon: 'लवकरच येत आहे',
        ai_online: 'AI ऑनलाइन',
        all_features: 'सर्व वैशिष्ट्ये',
        available_now: 'आता उपलब्ध',
        coming_soon_section: 'लवकरच येत आहे',
        ai_mode_toggle: 'AI मोड',
        ai_mode_live: 'लाइव्ह AI सपोर्ट',
        ai_mode_offline: 'ऑफलाइन AI मोड',
        journal_title: 'शेत जर्नल',
        journal_sub: 'आज तुमच्या शेतातील क्रियाकलाप नोंदवा.',
        history_btn: 'इतिहास',
        live_ai_advice: 'लाइव्ह AI कृषी सल्ला',
        offline_ai_advice: 'ऑफलाइन AI कृषी सल्ला',
        loading_chat: 'चॅट लोड होत आहे...',
        loading_insights: 'अंतर्दृष्टी लोड होत आहेत...',
        no_insights: 'AI अंतर्दृष्टी अनलॉक करण्यासाठी शेतातील क्रियाकलाप जोडा.',
        empty_today: "आजच्या शेतातील क्रियाकलापाची नोंद करण्यासाठी माइक टॅप करा किंवा खाली टाइप करा 🌾",
        input_placeholder_listening: 'ऐकत आहे...',
        input_placeholder_default: 'आज तुम्ही शेतात काय केले?',
        confirm_delete: 'तुम्हाला खात्री आहे की ही नोंद हटवायची आहे?',
        read_more: 'अधिक वाचा',
        show_less: 'कमी दाखवा',
        history_sidebar_title: 'डायरी इतिहास',
        history_sidebar_empty: 'कोणत्याही पूर्वीच्या नोंदी आढळल्या नाहीत.',
        mandi_title: 'मंडी व्हॉइस',
        mandi_subtitle: 'कोणत्याही पिकाबद्दल विचारा - AI बाजाराचा सल्ला देतो',
        mandi_select_state: '📍 तुमचे राज्य निवडा',
        mandi_choose_state: 'एक राज्य निवडा…',
        mandi_enter_crop: 'पिकाचे नाव प्रविष्ट करा',
        mandi_how_many_bags: 'किती पिशव्या?',
        mandi_get_price: 'किंमत आणि सल्ला मिळवा',
        mandi_nearby_mandis: '📍 जवळील मंडई',
        mandi_listen_advice: 'सल्ला ऐका',
        mandi_share_advice: 'सल्ला शेअर करा',
        scan_title: 'पीक स्कॅन करा',
        scan_subtitle: 'फोटोने रोग लगेच ओळखा',
        scan_take_photo: 'फोटो घ्या',
        scan_upload: 'फोटो अपलोड करा',
        scan_button: 'आता स्कॅन करा',
        scan_select_state: 'तुमचे राज्य निवडा',
        scan_confidence: 'विश्वासार्हता',
        scan_treatment: 'उपचार सल्ला',
        scan_organic: 'सेंद्रिय उपचार',
        scan_chemical: 'रासायनिक उपचार',
        scan_prevention: 'प्रतिबंधात्मक उपाय',
        scan_nearby: 'जवळच्या कृषी दुकाने',
        scan_listen: 'निदान ऐका',
        scan_recent: 'अलीकडील स्कॅन',
        scan_severity_low: 'कमी तीव्रता',
        scan_severity_medium: 'मध्यम तीव्रता',
        scan_severity_high: 'जास्त तीव्रता',
        crop_wheat: 'गहू',
        crop_rice: 'तांदूळ',
        crop_maize: 'मका',
        crop_cotton: 'कापूस',
        crop_soybean: 'सोयाबीन',
        crop_tomato: 'टोमॅटो',
        crop_onion: 'कांदा',
        crop_potato: 'बटाटा',
        state_maharashtra: 'महाराष्ट्र',
        state_punjab: 'पंजाब',
        state_haryana: 'हरियाणा',
        state_up: 'उत्तर प्रदेश',
        state_mp: 'मध्य प्रदेश',
        state_rajasthan: 'राजस्थान',
        state_bihar: 'बिहार',
        state_gujarat: 'गुजरात',
        state_karnataka: 'कर्नाटक',
        state_ap: 'आंध्र प्रदेश',
    },
    'বাংলা': {
        greeting: 'নমস্কার, আন্না',
        subtitle: 'কৃষি-সাথী আজ আপনাকে কীভাবে সাহায্য করতে পারে?',
        card_scan: 'রোগ স্ক্যান',
        card_scan_sub: 'তাত্ক্ষণিকভাবে ফসলের রোগ সনাক্ত করুন',
        card_advisory: 'ভয়েস বাজার দর',
        card_advisory_sub: 'রিয়েল-টাইম ফসলের দামের জন্য কথা বলুন',
        card_diary: 'ফসল ডায়েরি',
        card_diary_sub: 'কার্যকলাপ এবং খরচ ট্র্যাক করুন',
        card_risk: 'ঝুঁকি সতর্কতা',
        card_risk_sub: 'এআই-চালিত সতর্কতা',
        card_lunar: 'Lunar Planting',
        card_lunar_sub: 'Smart calendar guide',
        nav_home: 'হোম',
        nav_scan: 'ফসল স্ক্যান',
        nav_diary: 'ফসল ডায়েরি',
        nav_voice: 'ভয়েস ফসল',
        fab_ask: 'সহায়ককে জিজ্ঞাসা করুন',
        live: 'লাইভ',
        coming_soon: 'শীঘ্রই আসছে',
        ai_online: 'এআই অনলাইন',
        all_features: 'সব বৈশিষ্ট্য',
        available_now: 'এখন উপলব্ধ',
        coming_soon_section: 'শীঘ্রই আসছে',
        ai_mode_toggle: 'এআই মোড',
        ai_mode_live: 'লাইভ এআই সমর্থন',
        ai_mode_offline: 'অফলাইন এআই মোড',
        journal_title: 'খামার জার্নাল',
        journal_sub: 'আজ আপনার খামারের কার্যক্রম রেকর্ড করুন।',
        history_btn: 'ইতিহাস',
        live_ai_advice: 'লাইভ এআই খামার পরামর্শ',
        offline_ai_advice: 'অফলাইন এআই খামার পরামর্শ',
        loading_chat: 'চ্যাট লোড হচ্ছে...',
        loading_insights: 'অন্তর্দৃষ্টি লোড হচ্ছে...',
        no_insights: 'এআই অন্তর্দৃষ্টি আনলক করতে খামারের কার্যক্রম যোগ করুন।',
        empty_today: "আজকের খামারের কার্যক্রম রেকর্ড করতে মাইক ট্যাপ করুন বা নিচে টাইপ করুন 🌾",
        input_placeholder_listening: 'শুনছে...',
        input_placeholder_default: 'আজ আপনি খামারে কী করলেন?',
        confirm_delete: 'আপনি কি নিশ্চিত যে এটি মুছতে চান?',
        read_more: 'আরও পড়ুন',
        show_less: 'কম দেখান',
        history_sidebar_title: 'ডায়েরি ইতিহাস',
        history_sidebar_empty: 'অতীতের কোনো এন্ট্রি পাওয়া যায়নি.',
        mandi_title: 'মান্ডি ভয়েস',
        mandi_subtitle: 'যেকোনো ফসল সম্পর্কে জিজ্ঞাসা করুন - এআই বাজারের পরামর্শ দেয়',
        mandi_select_state: '📍 আপনার রাজ্য নির্বাচন করুন',
        mandi_choose_state: 'একটি রাজ্য চয়ন করুন…',
        mandi_enter_crop: 'ফসলের নাম লিখুন',
        mandi_how_many_bags: 'কতগুলো বস্তা?',
        mandi_get_price: 'দাম এবং পরামর্শ পান',
        mandi_nearby_mandis: '📍 কাছাকাছি মান্ডি',
        mandi_listen_advice: 'পরামর্শ শুনুন',
        mandi_share_advice: 'পরামর্শ শেয়ার করুন',
        scan_title: 'ফসল স্ক্যান করুন',
        scan_subtitle: 'ছবি থেকে রোগ তাৎক্ষণিক শনাক্ত করুন',
        scan_take_photo: 'ছবি তুলুন',
        scan_upload: 'ছবি আপলোড করুন',
        scan_button: 'এখনই স্ক্যান করুন',
        scan_select_state: 'আপনার রাজ্য বেছে নিন',
        scan_confidence: 'আস্থা',
        scan_treatment: 'চিকিৎসা পরামর্শ',
        scan_organic: 'জৈব চিকিৎসা',
        scan_chemical: 'রাসায়নিক চিকিৎসা',
        scan_prevention: 'প্রতিরোধমূলক ব্যবস্থা',
        scan_nearby: 'কাছের কৃষি দোকান',
        scan_listen: 'রোগ নির্ণয় শুনুন',
        scan_recent: 'সাম্প্রতিক স্ক্যান',
        scan_severity_low: 'কম তীব্রতা',
        scan_severity_medium: 'মাঝারি তীব্রতা',
        scan_severity_high: 'উচ্চ তীব্রতা',
        crop_wheat: 'গম',
        crop_rice: 'ধান',
        crop_maize: 'ভুট্টা',
        crop_cotton: 'তুলা',
        crop_soybean: 'সয়াবিন',
        crop_tomato: 'টমেটো',
        crop_onion: 'পেঁয়াজ',
        crop_potato: 'আলু',
        state_maharashtra: 'মহারাষ্ট্র',
        state_punjab: 'পাঞ্জাব',
        state_haryana: 'হরিয়ানা',
        state_up: 'উত্তর প্রদেশ',
        state_mp: 'মধ্যপ্রদেশ',
        state_rajasthan: 'রাজস্থান',
        state_bihar: 'বিহার',
        state_gujarat: 'গুজরাট',
        state_karnataka: 'কর্ণাটক',
        state_ap: 'অন্ধ্র প্রদেশ',
    },
    'ਪੰਜਾਬੀ': {
        greeting: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, ਅੰਨਾ',
        subtitle: 'ਕ੍ਰਿਸ਼ੀ-ਸਾਥੀ ਅੱਜ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹੈ?',
        card_scan: 'ਬਿਮਾਰੀ ਸਕੈਨ',
        card_scan_sub: 'ਫ਼ਸਲ ਦੀ ਬਿਮਾਰੀ ਦਾ ਤੁਰੰਤ ਪਤਾ ਲਗਾਓ',
        card_advisory: 'ਵੌਇਸ ਮਾਰਕੀਟ ਕੀਮਤ',
        card_advisory_sub: 'ਅਸਲ-ਸਮੇਂ ਦੀ ਫ਼ਸਲ ਦੀ ਕੀਮਤ ਲਈ ਬੋਲੋ',
        card_diary: 'ਫ਼ਸਲ ਡਾਇਰੀ',
        card_diary_sub: 'ਗਤੀਵਿਧੀਆਂ ਅਤੇ ਖਰਚਿਆਂ ਨੂੰ ਟਰੈਕ ਕਰੋ',
        card_risk: 'ਜੋਖਮ ਚੇਤਾਵਨੀਆਂ',
        card_risk_sub: 'AI-ਸੰਚਾਲਿਤ ਚੇਤਾਵਨੀਆਂ',
        card_lunar: 'ਲੂਨਰ ਪਲਾਂਟਿੰਗ',
        card_lunar_sub: 'ਸਮਾਰਟ ਕੈਲੰਡਰ ਗਾਈਡ',
        nav_home: 'ਹੋਮ',
        nav_scan: 'ਫ਼ਸਲ ਸਕੈਨ',
        nav_diary: 'ਫ਼ਸਲ ਡਾਇਰੀ',
        nav_voice: 'ਵੌਇਸ ਫ਼ਸਲ',
        fab_ask: 'ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ',
        live: 'ਲਾਈਵ',
        coming_soon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
        ai_online: 'AI ਔਨਲਾਈਨ',
        all_features: 'ਸਾਰੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
        available_now: 'ਹੁਣ ਉਪਲਬਧ ਹੈ',
        coming_soon_section: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
        ai_mode_toggle: 'AI ਮੋਡ',
        ai_mode_live: 'ਲਾਈਵ AI ਸਹਾਇਤਾ',
        ai_mode_offline: 'ਔਫਲਾਈਨ AI ਮੋਡ',
        journal_title: 'ਫਾਰਮ ਜਰਨਲ',
        journal_sub: 'ਅੱਜ ਆਪਣੀਆਂ ਖੇਤ ਦੀਆਂ ਗਤੀਵਿਧੀਆਂ ਨੂੰ ਰਿਕਾਰਡ ਕਰੋ।',
        history_btn: 'ਇਤਿਹਾਸ',
        live_ai_advice: 'ਲਾਈਵ AI ਖੇਤੀ ਸਲਾਹ',
        offline_ai_advice: 'ਔਫਲਾਈਨ AI ਖੇਤੀ ਸਲਾਹ',
        loading_chat: 'ਚੈਟ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
        loading_insights: 'ਜਾਣਕਾਰੀ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...',
        no_insights: 'AI ਜਾਣਕਾਰੀ ਅਨਲੌਕ ਕਰਨ ਲਈ ਖੇਤ ਦੀਆਂ ਗਤੀਵਿਧੀਆਂ ਸ਼ਾਮਲ ਕਰੋ।',
        empty_today: "ਅੱਜ ਦੀ ਖੇਤ ਦੀ ਗਤੀਵਿਧੀ ਨੂੰ ਰਿਕਾਰਡ ਕਰਨ ਲਈ ਮਾਈਕ 'ਤੇ ਟੈਪ ਕਰੋ ਜਾਂ ਹੇਠਾਂ ਟਾਈਪ ਕਰੋ 🌾",
        input_placeholder_listening: 'ਸੁਣ ਰਿਹਾ ਹੈ...',
        input_placeholder_default: 'ਅੱਜ ਤੁਸੀਂ ਖੇਤ ਵਿੱਚ ਕੀ ਕੀਤਾ?',
        confirm_delete: 'ਕੀ ਤੁਸੀਂ ਯਕੀਨਨ ਇਸ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
        read_more: 'ਹੋਰ ਪੜ੍ਹੋ',
        show_less: 'ਘੱਟ ਦਿਖਾਓ',
        history_sidebar_title: 'ਡਾਇਰੀ ਇਤਿਹਾਸ',
        history_sidebar_empty: 'ਕੋਈ ਪਿਛਲੀ ਐਂਟਰੀ ਨਹੀਂ ਮਿਲੀ.',
        mandi_title: 'ਮੰਡੀ ਵੌਇਸ',
        mandi_subtitle: 'ਕਿਸੇ ਵੀ ਫਸਲ ਬਾਰੇ ਪੁੱਛੋ - AI ਮਾਰਕੀਟ ਦੀ ਸਲਾਹ ਦਿੰਦਾ ਹੈ',
        mandi_select_state: '📍 ਆਪਣਾ ਰਾਜ ਚੁਣੋ',
        mandi_choose_state: 'ਇੱਕ ਰਾਜ ਚੁਣੋ…',
        mandi_enter_crop: 'ਫਸਲ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
        mandi_how_many_bags: 'ਕਿੰਨੀਆਂ ਬੋਰੀਆਂ?',
        mandi_get_price: 'ਕੀਮਤ ਅਤੇ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ',
        mandi_nearby_mandis: '📍 ਨੇੜਲੀਆਂ ਮੰਡੀਆਂ',
        mandi_listen_advice: 'ਸਲਾਹ ਸੁਣੋ',
        mandi_share_advice: 'ਸਲਾਹ ਸਾਂਝੀ ਕਰੋ',
        scan_title: 'ਫਸਲ ਸਕੈਨ ਕਰੋ',
        scan_subtitle: 'ਫੋਟੋ ਤੋਂ ਬਿਮਾਰੀ ਤੁਰੰਤ ਪਛਾਣੋ',
        scan_take_photo: 'ਫੋਟੋ ਲਓ',
        scan_upload: 'ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
        scan_button: 'ਹੁਣੇ ਸਕੈਨ ਕਰੋ',
        scan_select_state: 'ਆਪਣਾ ਰਾਜ ਚੁਣੋ',
        scan_confidence: 'ਭਰੋਸੇਯੋਗਤਾ',
        scan_treatment: 'ਇਲਾਜ ਸਲਾਹ',
        scan_organic: 'ਜੈਵਿਕ ਇਲਾਜ',
        scan_chemical: 'ਰਸਾਇਣਕ ਇਲਾਜ',
        scan_prevention: 'ਰੋਕਥਾਮ ਦੇ ਉਪਾਅ',
        scan_nearby: 'ਨੇੜੇ ਦੀਆਂ ਖੇਤੀ ਦੁਕਾਨਾਂ',
        scan_listen: 'ਨਿਦਾਨ ਸੁਣੋ',
        scan_recent: 'ਹਾਲੀਆ ਸਕੈਨ',
        scan_severity_low: 'ਘੱਟ ਗੰਭੀਰ',
        scan_severity_medium: 'ਮੱਧਮ ਗੰਭੀਰ',
        scan_severity_high: 'ਵੱਧ ਗੰਭੀਰ',
        crop_wheat: 'ਕਣਕ',
        crop_rice: 'ਝੋਨਾ',
        crop_maize: 'ਮੱਕੀ',
        crop_cotton: 'ਕਪਾਹ',
        crop_soybean: 'ਸੋਇਆਬੀਨ',
        crop_tomato: 'ਟਮਾਟਰ',
        crop_onion: 'ਪਿਆਜ਼',
        crop_potato: 'ਆਲੂ',
        state_maharashtra: 'ਮਹਾਰਾਸ਼ਟਰ',
        state_punjab: 'ਪੰਜਾਬ',
        state_haryana: 'ਹਰਿਆਣਾ',
        state_up: 'ਉੱਤਰ ਪ੍ਰਦੇਸ਼',
        state_mp: 'ਮੱਧ ਪ੍ਰਦੇਸ਼',
        state_rajasthan: 'ਰਾਜਸਥਾਨ',
        state_bihar: 'ਬਿਹਾਰ',
        state_gujarat: 'ਗੁਜਰਾਤ',
        state_karnataka: 'ਕਰਨਾਟਕ',
        state_ap: 'ਆਂਧਰਾ ਪ੍ਰਦੇਸ਼',
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: keyof Translations['English']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>('English');

    useEffect(() => {
        const saved = localStorage.getItem('krishi_lang');
        if (saved && Object.keys(translations).includes(saved)) {
            setLanguageState(saved as Language);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('krishi_lang', lang);
    };

    const t = (key: keyof Translations['English']) => {
        return translations[language][key] || translations['English'][key];
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
